sudo: required
dist: trusty

language: python
python:
    - "2.7"
# command to install dependencies

before_install:
    - export CHROME_BIN=chromium-browser
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - sudo apt-get update
    - sudo apt-get install -y libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb

install:
    - pip install -r requirements.txt
# command to run tests

script:
    - python setup.py install
    - pip install -r requirements.txt
    - cd sandstone/client
    - npm install
    - cd /home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages
    - cd sandstone-*-py2.7.egg/
    - rm -rf sandstone/
    - ln -s ~/build/saurabhsood91/sandstone-ide/sandstone/
    - cd ~/build/saurabhsood91/sandstone-ide/sandstone/scripts
    - python run_server_tests.py
    - python run_client_tests.py
