sudo: required
dist: trusty

language: python
python:
    - "2.7"

notifications:
    slack: rmacc:XuJOFyi7wxFivfqbHS6KDMSw

before_install:
    - export CHROME_BIN=chromium-browser
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - sudo apt-get update
    - sudo apt-get install -y libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb

install:
    - pip install -r requirements.txt
# command to run tests

script:
    - export PROJECT_ROOT=$(pwd)
    - export PATH_FILE=/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/sandstone.pth
    - echo $PROJECT_ROOT > $PATH_FILE
    - pip install -r requirements.txt
    - cd sandstone/client
    - npm install
    - cd $PROJECT_ROOT/sandstone/scripts
    - python run_server_tests.py
    - python run_client_tests.py
    - cd $PROJECT_ROOT
    - rm $PATH_FILE
    - python setup.py install
